apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: turinghatch
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  type: ClusterIP
---
# Headless service required by StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: turinghatch
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
