apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - httproute.yaml
images:
  - name: ivplay4689/turinghatch
    newTag: ruthless-execution-be-1.0.0
