apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mdnajimahmed/oracle-cloud-free-infra.git
    targetRevision: main
    path: k8s/apps/namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
