apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mdnajimahmed/oracle-cloud-free-infra.git
    targetRevision: main
    path: k8s/apps/ruthless-execution/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: ruthless-execution
  ignoreDifferences:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      jsonPointers:
        - /spec/rules/0/backendRefs/0/group
        - /spec/rules/0/backendRefs/0/kind
        - /spec/rules/0/backendRefs/0/weight
        - /spec/parentRefs/0/group
        - /spec/parentRefs/0/kind
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
