apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: ruthless-execution
data:
  default.conf: |
    server {
        listen 8080;
        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri /index.html;
        }
    }
